# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


labels:
- includeSelectors: false
  pairs:
    app-name: elasticsearch

resources:
- elastic-stateful-set.yaml
- headless-service.yaml
- kibana.yaml
- network.yaml

configMapGenerator:
- name: app-configmap-1
  envs:
  - app.properties

# secretGenerator:
# - name: app-secret-1
#   envs:
#   - app-secrets.properties

replacements:
- source:
    kind: ConfigMap
    name: app-configmap-1
    fieldPath: data.ELASTICSEARCH_IMAGE
  targets:
  - select:
      kind: StatefulSet
      name: es-cluster
    fieldPaths:
    - spec.template.spec.containers.0.image
- source:
    kind: ConfigMap
    name: app-configmap-1
    fieldPath: data.BUSYBOX_IMAGE
  targets:
  - select:
      kind: StatefulSet
      name: es-cluster
    fieldPaths:
    - spec.template.spec.initContainers.0.image
    - spec.template.spec.initContainers.1.image
    - spec.template.spec.initContainers.2.image
- source:
    kind: ConfigMap
    name: app-configmap-1
    fieldPath: data.KIBANA_IMAGE
  targets:
  - select:
      kind: Deployment
      name: kibana
    fieldPaths:
    - spec.template.spec.containers.0.image
