# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: v1
kind: Namespace
metadata:
  name: shared-services
  labels:
    kubernetes.io/metadata.name: shared-services
    gdc.google.com/tenant-id: shared-services
    gdc.google.com/tier: platform-shared

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shared-backend
  namespace: shared-services
  labels:
    app: shared-backend
    tier: backend
    tenant: shared-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shared-backend
  template:
    metadata:
      labels:
        app: shared-backend
        tier: backend
        tenant: shared-services
    spec:
      containers:
        - name: echo-server
          image: harbor.zone1.google.gdch.test/library/http-echo:0.2.3
          args:
            - "-listen=:8080"
            - "-text=Response from GDC Shared Backend Service [STATUS: 200 OK]"
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL

---
apiVersion: v1
kind: Service
metadata:
  name: shared-backend
  namespace: shared-services
  labels:
    app: shared-backend
    tenant: shared-services
spec:
  type: ClusterIP
  selector:
    app: shared-backend
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
